-- Migration: Remove team_id columns from t_matches_final and t_matches_live
-- Date: 2026-02-05
-- Method: Manual migration script (scripts/remove-team-id-columns.mjs)
--
-- This migration was executed using a custom script because SQLite does not support
-- ALTER TABLE DROP COLUMN. The tables were recreated with the new schema.
--
-- Changes:
-- - Removed team1_id (TEXT) from t_matches_final
-- - Removed team2_id (TEXT) from t_matches_final
-- - Removed winner_team_id (TEXT) from t_matches_final
-- - Removed team1_id (TEXT) from t_matches_live
-- - Removed team2_id (TEXT) from t_matches_live
-- - Removed winner_team_id (TEXT) from t_matches_live
--
-- Retained columns:
-- - team1_tournament_team_id (INTEGER)
-- - team2_tournament_team_id (INTEGER)
-- - winner_tournament_team_id (INTEGER)

-- This SQL file is for documentation purposes only.
-- The actual migration was performed by scripts/remove-team-id-columns.mjs
-- which recreated the tables using the following pattern:
--
-- 1. PRAGMA foreign_keys=OFF
-- 2. CREATE TABLE t_matches_final_new (...)
-- 3. INSERT INTO t_matches_final_new SELECT ... FROM t_matches_final
-- 4. DROP TABLE t_matches_final
-- 5. ALTER TABLE t_matches_final_new RENAME TO t_matches_final
-- 6. CREATE INDEX ...
-- 7. PRAGMA foreign_keys=ON
--
-- (Same process for t_matches_live)

-- ⚠️ DO NOT EXECUTE THIS FILE
-- The migration has already been applied to the database.
