ALTER TABLE t_tournaments ADD COLUMN preliminary_format_type TEXT;
ALTER TABLE t_tournaments ADD COLUMN final_format_type TEXT;
ALTER TABLE t_tournaments ADD COLUMN phases TEXT;
ALTER TABLE t_matches_live ADD COLUMN phase TEXT;
ALTER TABLE t_matches_live ADD COLUMN match_type TEXT;
ALTER TABLE t_matches_live ADD COLUMN round_name TEXT;
ALTER TABLE t_matches_live ADD COLUMN block_name TEXT;
ALTER TABLE t_matches_live ADD COLUMN team1_source TEXT;
ALTER TABLE t_matches_live ADD COLUMN team2_source TEXT;
ALTER TABLE t_matches_live ADD COLUMN day_number INTEGER;
ALTER TABLE t_matches_live ADD COLUMN execution_priority INTEGER;
ALTER TABLE t_matches_live ADD COLUMN suggested_start_time TEXT;
ALTER TABLE t_matches_live ADD COLUMN loser_position_start INTEGER;
ALTER TABLE t_matches_live ADD COLUMN loser_position_end INTEGER;
ALTER TABLE t_matches_live ADD COLUMN position_note TEXT;
ALTER TABLE t_matches_live ADD COLUMN winner_position INTEGER;
ALTER TABLE t_matches_live ADD COLUMN is_bye_match INTEGER DEFAULT 0;
ALTER TABLE t_matches_live ADD COLUMN matchday INTEGER;
ALTER TABLE t_matches_live ADD COLUMN cycle INTEGER DEFAULT 1;
ALTER TABLE t_matches_final ADD COLUMN phase TEXT;
ALTER TABLE t_matches_final ADD COLUMN match_type TEXT;
ALTER TABLE t_matches_final ADD COLUMN round_name TEXT;
ALTER TABLE t_matches_final ADD COLUMN block_name TEXT;
ALTER TABLE t_matches_final ADD COLUMN team1_source TEXT;
ALTER TABLE t_matches_final ADD COLUMN team2_source TEXT;
ALTER TABLE t_matches_final ADD COLUMN day_number INTEGER;
ALTER TABLE t_matches_final ADD COLUMN execution_priority INTEGER;
ALTER TABLE t_matches_final ADD COLUMN suggested_start_time TEXT;
ALTER TABLE t_matches_final ADD COLUMN loser_position_start INTEGER;
ALTER TABLE t_matches_final ADD COLUMN loser_position_end INTEGER;
ALTER TABLE t_matches_final ADD COLUMN position_note TEXT;
ALTER TABLE t_matches_final ADD COLUMN winner_position INTEGER;
ALTER TABLE t_matches_final ADD COLUMN is_bye_match INTEGER DEFAULT 0;
ALTER TABLE t_matches_final ADD COLUMN matchday INTEGER;
ALTER TABLE t_matches_final ADD COLUMN cycle INTEGER DEFAULT 1;
